// Generated by CoffeeScript 1.9.1
(function() {
  var Admin;

  module.exports = Admin = (function() {
    function Admin(master, args) {
      this.master = master;
      this.args = args;
    }


    /**
    * admin actions function
     */

    Admin.prototype.init = function() {
      var db;
      if (this.args[0] === 'dbUpdate') {
        db = this.master.factory('db');
        db.updateDbSchema(true);
      }
      if (this.args[0] === 'dbInstall') {
        db = this.master.factory('db');
        return db.updateDbSchema(false);
      }
    };

    return Admin;

  })();

}).call(this);
