// Generated by CoffeeScript 1.9.1
(function() {
  var Done;

  module.exports = Done = (function() {
    function Done(master, args) {
      this.master = master;
      this.args = args;
    }

    Done.prototype.init = function() {
      return this.setDone();
    };


    /**
    * set current Task to done and print it
     */

    Done.prototype.setDone = function() {
      var IO, msg, ref, todo;
      ref = this.master.factory("IO", "cmd/todo", "config/messages.noTaskOpen"), IO = ref[0], todo = ref[1], msg = ref[2];
      return todo.getCurrentTask(function(task) {
        var attr, where;
        if (task === null) {
          IO.println(msg);
          return process.exit();
        } else {
          attr = {
            done_at: new Date()
          };
          where = {
            where: {
              id: task.id
            }
          };
          return task.update(attr, where).then(function() {
            return IO.printTask(task, function() {
              return todo.init();
            });
          })["catch"](function(err) {
            return console.log(err);
          });
        }
      });
    };

    return Done;

  })();

  module.exports = Done;

}).call(this);
