// Generated by CoffeeScript 1.4.0
(function() {
  var Done;

  module.exports = Done = (function() {

    function Done(master, args) {
      this.master = master;
      this.args = args;
    }

    Done.prototype.init = function() {
      var _ref;
      _ref = this.master.coreModels("IO", "db"), this.IO = _ref[0], this.db = _ref[1];
      return this.setDone();
    };

    /**
    * set current Task to done and print it
    */


    Done.prototype.setDone = function() {
      var IO;
      IO = this.IO;
      return this.db.init(function(db) {
        return db.getCurrentTask(function(task) {
          task.setDoneAt(new Date());
          return db.updateTask(task, function() {
            IO.println(task.toString());
            return process.exit();
          });
        });
      });
    };

    return Done;

  })();

  module.exports = Done;

}).call(this);
