// Generated by CoffeeScript 1.4.0
(function() {
  var Done;

  Done = (function() {
    var IO, Task, args, db, master;
    Task = require('../model/Task.js');
    db = null;
    IO = null;
    master = null;
    args = null;
    return {
      /**
      * init Done model, args are passed
      * to receive model options
      * @param _args array
      * @param _db Db_ref
      * @param _master WoQu_ref
      */

      init: function(_args, _master) {
        var _ref;
        args = _args;
        master = _master;
        _ref = master.coreModels("IO", "db"), IO = _ref[0], db = _ref[1];
        return Done.setDone();
      },
      /**
      * set current Task to done and print it
      */

      setDone: function(task) {
        db.init(function(db) {});
        return db.getCurrentTask(function(task) {
          task.setDoneAt(new Date());
          return db.updateTask(task, function() {
            IO.println(task.toString());
            return process.exit();
          });
        });
      }
    };
  })();

  module.exports = Done;

}).call(this);
