// Generated by CoffeeScript 1.9.1
(function() {
  var Info;

  module.exports = Info = (function() {
    function Info(master, args) {
      this.master = master;
      this.args = args;
    }

    Info.prototype.init = function() {
      return this.addInfo();
    };


    /**
    * set current Task to done and print it
     */

    Info.prototype.addInfo = function() {
      var IO, msg, ref, text, todo;
      ref = this.master.factory('cmd/todo', 'model/Info', 'IO', 'config/messages.noTaskOpen'), todo = ref[0], Info = ref[1], IO = ref[2], msg = ref[3];
      text = this.args[0];
      return todo.getCurrentTask(function(task) {
        var info;
        if (task === null) {
          IO.println(msg);
          return process.exit();
        } else {
          info = Info.build({
            text: text
          });
          return info.save()["catch"](IO.error).then(function() {
            return task.addInfo(info).then(function() {
              return todo.init();
            });
          });
        }
      });
    };

    return Info;

  })();

}).call(this);
