// Generated by CoffeeScript 1.9.1
(function() {
  var Log;

  module.exports = Log = (function() {
    function Log(master, args) {
      var ref;
      this.master = master;
      this.args = args;
      ref = this.master.factory("IO", "db"), this.IO = ref[0], this.db = ref[1];
    }

    Log.prototype.init = function() {
      return this.logInfo();
    };


    /**
    * set current Task to done and print it
     */

    Log.prototype.logInfo = function() {
      return this.IO.println("jf lösjfl ajsfjlöasj fl");
    };

    return Log;

  })();

  module.exports = Log;

}).call(this);
