// Generated by CoffeeScript 1.9.1
(function() {
  var Log;

  module.exports = Log = (function() {
    function Log(master, args) {
      this.master = master;
      this.args = args;
    }

    Log.prototype.init = function() {
      return this.logInfo();
    };


    /**
    * set current Task to done and print it
     */

    Log.prototype.logInfo = function() {
      var IO, LoggedWork, ref, text, todo;
      ref = this.master.factory('cmd/todo', 'model/LoggedWork', 'IO'), todo = ref[0], LoggedWork = ref[1], IO = ref[2];
      text = this.args[0];
      return todo.getCurrentTask(function(task) {
        var work;
        if (task === null) {
          IO.println("Currently there is no task open");
          return process.exit();
        } else {
          work = LoggedWork.build({
            text: text
          });
          return work.save()["catch"](IO.error).then(function() {
            return task.addLoggedWork(work).then(function() {
              return todo.init();
            });
          });
        }
      });
    };

    return Log;

  })();

  module.exports = Log;

}).call(this);
