// Generated by CoffeeScript 1.9.1
(function() {
  var Next;

  module.exports = Next = (function() {
    function Next(master, args) {
      this.master = master;
      this.args = args;
    }

    Next.prototype.init = function() {
      this.db = this.master.getDb();
      return this.moveCurTaskBackwards();
    };


    /**
    * update Task to increase postponed
     */

    Next.prototype.moveCurTaskBackwards = function() {
      var todo;
      todo = this.master.factory('todo');
      return todo.getCurrentTask(function(task) {
        var postponed;
        postponed = task.getDataValue("postponed");
        return task.updateAttributes({
          postponed: postponed + 1
        }).then(function() {
          return todo.init();
        });
      });
    };

    return Next;

  })();

  module.exports = Next;

}).call(this);
