// Generated by CoffeeScript 1.9.1
(function() {
  var Test;

  module.exports = Test = (function() {
    function Test(master, args) {
      this.master = master;
      this.args = args;
    }


    /**
    * test function
     */

    Test.prototype.init = function() {
      var Info, LoggedWork, Task, ref;
      console.log("do tests here");
      ref = this.master.factory('model/Task', 'model/LoggedWork', 'model/Info'), Task = ref[0], LoggedWork = ref[1], Info = ref[2];
      return Task.findAll({
        where: {
          id: 1
        },
        include: [Info, LoggedWork]
      }).then(function(fulltask) {
        fulltask[0].Infos.forEach(function(info) {
          return console.log(info.text);
        });
        return fulltask[0].LoggedWorks.forEach(function(work) {
          return console.log(work.text);
        });
      });
    };

    return Test;

  })();

}).call(this);
