// Generated by CoffeeScript 1.9.1
(function() {
  var Test;

  module.exports = Test = (function() {
    function Test(master, args) {
      this.master = master;
      this.args = args;
    }


    /**
    * test function
     */

    Test.prototype.init = function() {
      var task;
      console.log("do tests here");
      task = this.master.factory('db').getModel('Task').build();
      task.description = "mal wieder ein test";
      task.postponed = 0;
      task.test = "will this new field be added";
      return task.save()["catch"](function(err) {
        return console.log(err);
      }).then(function(task) {
        return console.log("success " + task.getDataValue("id"));
      });

      /*
      task.description = "new sequelize test"
      task.postponed = 0
      task.done_at = null
      
      task.save()
        .catch (err) -> console.log(err)
        .then (task) -> console.log("success " + task.getDataValue("id"))
       */
    };

    return Test;

  })();

}).call(this);
