// Generated by CoffeeScript 1.9.1
(function() {
  var Todo;

  module.exports = Todo = (function() {
    function Todo(master, args) {
      this.master = master;
      this.args = args;
    }

    Todo.prototype.init = function() {
      return this.getTodo();
    };

    Todo.prototype.getCurrentTask = function(cb) {
      return this.master.factory('model/Task').find({
        where: ["done_at is null"],
        order: 'id + postponed, postponed, id ASC',
        limit: 1
      }).then(cb);
    };


    /**
    * get current Task from database
     */

    Todo.prototype.getTodo = function() {
      var IO;
      IO = this.master.factory('IO');
      return this.getCurrentTask(function(task) {
        return IO.printTask(task);
      });
    };

    return Todo;

  })();

}).call(this);
