// Generated by CoffeeScript 1.9.1
(function() {
  var Todo;

  module.exports = Todo = (function() {
    function Todo(master, args) {
      var ref;
      this.master = master;
      this.args = args;
      ref = this.master.coreModels("db", "IO"), this.db = ref[0], this.IO = ref[1];
    }

    Todo.prototype.init = function() {
      return this.getTodo();
    };

    Todo.prototype.getCurrentTask = function(cb) {
      return this.master.getDb().getModels().Task.find({
        where: ["done_at is null"],
        order: 'id + postponed, postponed, id ASC',
        limit: 1
      }).then(cb);
    };


    /**
    * get current Task from database
     */

    Todo.prototype.getTodo = function() {
      var IO, Task;
      IO = this.IO;
      Task = this.master.getTask();
      return this.getCurrentTask(function(res) {
        var task;
        task = new Task(res);
        IO.println(task.toString());
        return process.exit();
      });
    };

    return Todo;

  })();

  module.exports = Todo;

}).call(this);
