// Generated by CoffeeScript 1.9.1
(function() {
  var LoggedWork,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = LoggedWork = (function(superClass) {
    extend(LoggedWork, superClass);

    function LoggedWork(ormDataModel) {
      if (ormDataModel == null) {
        ormDataModel = null;
      }
      this.text = null;
    }

    LoggedWork.prototype.fromOrm = function(ormModel) {
      var dataValues;
      dataValues = ormModel.dataValues;
      return this.seText(dataValues.text);
    };

    LoggedWork.prototype.getText = function() {
      return this.text;
    };

    LoggedWork.prototype.setText = function(text) {
      this.text = text;
      return this;
    };

    return LoggedWork;

  })(require('./SuperModel'));

}).call(this);
