// Generated by CoffeeScript 1.4.0
(function() {
  var Task, moment;

  moment = require('moment');

  Task = (function() {

    function Task() {
      this.id = null;
      this.description = null;
      this.created_at = null;
      this.postponed = null;
      this.done_at = null;
    }

    Task.prototype.getId = function() {
      return this.id;
    };

    Task.prototype.setId = function(id) {
      this.id = id;
      return this;
    };

    Task.prototype.getDescription = function() {
      return this.description;
    };

    Task.prototype.setDescription = function(desc) {
      this.description = desc;
      return this;
    };

    Task.prototype.getCreatedAt = function() {
      return this.created_at;
    };

    Task.prototype.setCreatedAt = function(date) {
      this.created_at = date;
      return this;
    };

    Task.prototype.getPostponed = function() {
      return this.postponed;
    };

    Task.prototype.increasePostponed = function() {
      return this.postponed++;
    };

    Task.prototype.setPostponed = function(number) {
      this.postponed = number;
      return this;
    };

    Task.prototype.getDoneAt = function() {
      return this.done_at;
    };

    Task.prototype.setDoneAt = function(date) {
      this.done_at = date;
      return this;
    };

    Task.prototype.init = function(obj) {
      var key, val;
      for (key in obj) {
        val = obj[key];
        this[key] = val;
      }
      return this;
    };

    Task.prototype.to$Obj = function() {
      var arr, key, val;
      arr = {};
      for (key in this) {
        val = this[key];
        if (typeof val !== 'function') {
          arr['$' + key] = val instanceof Date ? val.getTime() : val;
        }
      }
      return arr;
    };

    Task.prototype.toString = function() {
      return "Task #" + this.id + " From: " + (moment(this.created_at).format('DD.MM.YYYY HH:mm:ss')) + "\n" + this.description + "\n[postponed]: " + this.postponed + "\n" + (this.done_at ? '[done]: ' + moment(this.done_at).format('DD.MM.YYYY HH:mm:ss') : ' ');
    };

    return Task;

  })();

  module.exports = Task;

}).call(this);
