// Generated by CoffeeScript 1.9.1
(function() {
  var CmdsFactory;

  module.exports = CmdsFactory = (function() {
    function CmdsFactory() {}

    CmdsFactory.subCommandsDir = './cmds/';

    CmdsFactory.coreDir = './core/cmds/';

    CmdsFactory.fs = require('fs');

    CmdsFactory.instances = {};

    CmdsFactory.master = null;

    CmdsFactory.setMaster = function(master) {
      this.master = master;
      return this;
    };

    CmdsFactory.get = function(name, args) {
      var model;
      if (args == null) {
        args = [];
      }
      name = this.toCoreModelName(name);
      if (this.instances[name]) {
        return this.instances[name];
      } else {
        model = this.getModel(name);
        return new model(this.master, args);
      }
    };

    CmdsFactory.getCoreDir = function() {
      return this.coreDir;
    };


    /**
    * ensure that sub comment is in model name format
    * (first char uppercase )
     */

    CmdsFactory.toCoreModelName = function(str) {
      var f;
      str += '';
      f = str.charAt(0).toUpperCase();
      return f + str.substr(1).toLowerCase();
    };


    /**
    * get sub model
    * @return subModel_ref
     */

    CmdsFactory.getModel = function(model) {
      var path, requirePath;
      path = CmdsFactory.coreDir + model + '.js';
      requirePath = CmdsFactory.subCommandsDir + model;
      if (CmdsFactory.fs.existsSync(path)) {
        return require(requirePath);
      } else {
        console.log("invalid command: " + model);
        return process.exit();
      }
    };

    return CmdsFactory;

  })();

}).call(this);
