// Generated by CoffeeScript 1.4.0
(function() {
  var Done;

  Done = (function() {
    var Task, args, db, master;
    Task = require('./model/Task.js');
    db = null;
    master = null;
    args = null;
    return {
      /**
      * init Done model, args are passed
      * to receive model options
      * @param _args array
      * @param _db Db_ref
      * @param _master WoQu_ref
      */

      init: function(_args, _db, _master) {
        args = _args;
        db = _db;
        master = _master;
        return Done.setDone();
      },
      /**
      * set current Task to done and print it
      */

      setDone: function(task) {
        db.init(function(db) {});
        return db.getCurrentTask(function(task) {
          task.setDoneAt(new Date());
          return db.updateTask(task, function() {
            return console.log(task.toString());
          });
        });
      }
    };
  })();

  module.exports = Done;

}).call(this);
