// Generated by CoffeeScript 1.9.1
(function() {
  var IO;

  IO = (function() {
    function IO(master) {
      this.master = master;
      this.readline = require('readline');
      this.term_ui = require('./term-ui/TermUI.js');
      this.rl = this.readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });
    }

    IO.prototype.printTaskOrmModel = function(model) {
      var Task, task;
      Task = this.master.getTask();
      task = new Task(model);
      return this.println(task.toString());
    };


    /**
    * print string in shell
    *
     */

    IO.prototype.print = function(str) {
      return this.term_ui.out(str);
    };


    /**
    * print string in shell with newline
    *
     */

    IO.prototype.println = function(str) {
      return this.term_ui.out(str + "\n");
    };


    /**
    * this provides an read line input for the shell
     */

    IO.prototype.readLine = function(question, cb) {
      var self;
      self = this;
      return this.rl.question(question, function(answer) {
        cb(answer, self);
        return self.rl.close();
      });
    };

    return IO;

  })();

  module.exports = IO;

}).call(this);
