// Generated by CoffeeScript 1.4.0
(function() {
  var Next;

  Next = (function() {
    var Task, args, db, master;
    Task = require('./model/Task.js');
    db = null;
    master = null;
    args = null;
    return {
      /**
        * init Next model, args are passed
        * to receive model options
        * @param _args array
        * @param _db Db_ref
        * @param _master WoQu_ref
      */

      init: function(_args, _db, _master) {
        args = _args;
        db = _db;
        master = _master;
        return Next.moveCurTaskBackwards();
      },
      /**
      * update Task to increase postponed
      * run woqu todo
      */

      moveCurTaskBackwards: function(task) {
        return db.init(function(db) {
          return db.getCurrentTask(function(task) {
            task.increasePostponed();
            return db.updateTask(task, master.getTodo);
          });
        });
      }
    };
  })();

  module.exports = Next;

}).call(this);
