// Generated by CoffeeScript 1.4.0
(function() {
  var Todo;

  Todo = (function() {
    var Task, args, db, master;
    Task = require('./model/Task.js');
    db = null;
    master = null;
    args = null;
    return {
      /**
      * init Todo model, args are passed
      * to receive model options
      * @param _args array
      * @param _db Db_ref
      * @param _master WoQu_ref
      */

      init: function(_args, _master) {
        args = _args;
        master = _master;
        db = master.getDb();
        return Todo.getTodo();
      },
      /**
      * get current Task from database
      */

      getTodo: function(task) {
        return db.init(function(db) {
          return db.getCurrentTask(function(task) {
            return console.log(task.toString());
          });
        });
      }
    };
  })();

  module.exports = Todo;

}).call(this);
