// Generated by CoffeeScript 1.4.0
(function() {
  var WoQu,
    __slice = [].slice;

  WoQu = (function() {
    var IO, Task, args, clicolor, coreDir, db, devMode, fs, subCommandsDir;
    db = require('./Db.js');
    Task = require('./model/Task.js');
    fs = require('fs');
    clicolor = require('cli-color');
    IO = require('./IO.js');
    args = null;
    subCommandsDir = './cmds/';
    coreDir = './core/cmds/';
    devMode = true;
    return {
      /**
      * start woqu app and handle args
      */

      run: function(_devMode) {
        devMode = _devMode;
        args = WoQu.getArgs();
        return WoQu.getModel(args[0]).init(args.slice(1), WoQu);
      },
      /**
      * ensure that sub comment is in model name format
      * (first char uppercase )
      */

      toCoreModelName: function(str) {
        var f;
        str += '';
        f = str.charAt(0).toUpperCase();
        return f + str.substr(1).toLowerCase();
      },
      /**
      * get relevant args
      * @return array
      */

      getArgs: function() {
        return process.argv.slice(2);
      },
      /**
      * get database model reference
      * @return Db_ref
      */

      getDb: function() {
        return db;
      },
      /**
      * get IO model reference
      * @return IO_ref
      */

      getIO: function() {
        return IO;
      },
      /**
      * get sub model
      * @return subModel_ref
      */

      getModel: function(str) {
        var model, path, requirePath;
        model = WoQu.toCoreModelName(str);
        path = coreDir + model + '.js';
        requirePath = subCommandsDir + model;
        if (fs.existsSync(path)) {
          return require(requirePath);
        } else {
          return {
            init: function() {
              return console.error("invalid command: " + str);
            }
          };
        }
      },
      /**
      * check if app is in development mode
      * @return boolean
      */

      isDevMode: function() {
        return devMode;
      },
      /**
      * cli color handle getter
      * @return cli-color_ref
      */

      getCliColor: function() {
        return clicolor;
      },
      /**
      # inline Model Getter
      */

      coreModels: function() {
        var i, models, name, names;
        names = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        models = [];
        for (i in names) {
          name = names[i];
          if (name === 'db') {
            models.push(db);
          }
          if (name === 'IO') {
            models.push(IO);
          }
          if (name === 'fs') {
            models.push(fs);
          }
          if (name === 'clicolor') {
            models.push(clicolor);
          }
        }
        return models;
      }
    };
  })();

  module.exports = WoQu;

}).call(this);
