// Generated by CoffeeScript 1.4.0
(function() {
  var WoQu;

  WoQu = (function() {
    var Task, args, db, subCommandsDir;
    db = require('./Db.js');
    Task = require('./model/Task.js');
    args = null;
    subCommandsDir = './';
    return {
      /**
      * start woqu app and handle args
      */

      run: function() {
        var model;
        args = WoQu.getArgs();
        model = WoQu.toCoreModelName(args[0]);
        return require(subCommandsDir + model).init(args.slice(1), db, WoQu);
      },
      /**
      * ensure that sub comment is in model name format
      * (first char uppercase )
      */

      toCoreModelName: function(str) {
        var f;
        str += '';
        f = str.charAt(0).toUpperCase();
        return f + str.substr(1).toLowerCase();
      },
      /**
      * get relevant args
      * @return array
      */

      getArgs: function() {
        return process.argv.slice(2);
      },
      /**
      * get database model reference
      * @return Db_ref
      */

      getDb: function() {
        return db;
      }
    };
  })();

  module.exports = WoQu;

}).call(this);
