// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('Info', {
      text: DataTypes.TEXT
    }, {
      instanceMethods: {},
      classMethods: {}
    });
  };

}).call(this);
