// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('Task', {
      description: DataTypes.TEXT,
      postponed: {
        type: DataTypes.INTEGER,
        allowNull: false,
        defaultValue: 0
      },
      done_at: DataTypes.DATE
    }, {
      instanceMethods: {
        postpone: function() {
          var postponeVal;
          postponeVal = this.getDataValue('postponed');
          if (typeof postponeVal === 'undefined') {
            postponeVal = 0;
          }
          postponeVal++;
          return this.setDataValue("postponed", postponeVal);
        }
      },
      classMethods: {}
    });
  };

}).call(this);
